SushiRoll.create(name: "Surf & Turf Roll", price: 12.95, primary_ingredient: "Cucumber", secondary_ingredient: "Fish Cake", user_id: 1)
SushiRoll.create(name: "Veggie Roll", price: 6.95 , primary_ingredient: "Cucumber", secondary_ingredient: "Carrot", user_id: 1)
SushiRoll.create(name: "Caterpillar Roll", price: 13.95 , primary_ingredient: "Avocado", secondary_ingredient: "Unagi", user_id: 1)
SushiRoll.create(name: "Spider Roll", price: 11.95, primary_ingredient: "Soft-Shell Crab", secondary_ingredient: "Avocado", user_id: 1)
SushiRoll.create(name: "Philly Roll", price: 8.98, primary_ingredient: "Cream Cheese", secondary_ingredient: "Avocado", user_id: 1)
SushiRoll.create(name: "California Roll", price: 6.95, primary_ingredient: "Krab", secondary_ingredient: "Avocado", user_id: 1)
SushiRoll.create(name: "Shrimp Tempura Roll", price: 13.95, primary_ingredient: "Shrimp", secondary_ingredient: "Avocado", user_id: 1)
SushiRoll.create(name: "Rainbow Roll", price: 14.95, primary_ingredient: "Krab", secondary_ingredient: "Tuna", user_id: 1)
SushiRoll.create(name: "Dragon Roll", price: 13.95, primary_ingredient: "Cucumber", secondary_ingredient: "Avocado", user_id: 1)
